#!/bin/bash

cp blockchain-client.jar  bonusPointsExchange/WEB-INF/lib/


cd bonusPointsExchange


OSTYPE="`arch`"

if [[ "$OSTYPE" == "s390x" ]]; then

  sudo zypper install java
  fastjar -cvf bonusPointsExchange.war *
  cd ..
  docker rm -f bonus
  docker rmi -f scut_bonuswar scut_bonus_war
  docker-compose -f docker-compose390.yml up -d

else
#  jar -cvf bonusPointsExchange.war *
  cd ..
  docker rm -f bonus
  docker rmi -f scut_bonuswar scut_bonus_war
  docker-compose up -d
fi

